# Generated by Django 5.1.6 on 2026-10-09 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sandbox_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sandbox_status', models.CharField(max_length=255)),
                ('behaviour_summary', models.TextField()),
                ('executed_on_server', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('APK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.malwarescanlog')),
            ],
        ),
    ]
