# Generated by Django 5.1.6 on 2026-10-09 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_malwarescanlog_confidence_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network_Scan_monitoring_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_host', models.CharField(max_length=255)),
                ('scanresult', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Monitoring', 'Monitoring'), ('Normal', 'Normal'), ('Suspicious', 'Suspicious'), ('DDoS Suspected', 'DDoS Suspected'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
    ]
